name: Applies Coding Standard configuration files in the repository
description: |
  Installs Python and indexes the CodeQL Coding Standard configuration files in the repository

runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install dependencies
      shell: bash
      run: ls ${{ github.action_path }}/../../..; python -m pip install -r ${{ github.action_path }}/../../../scripts/configuration/requirements.txt
    - name: Process files
      shell: bash
      run: python ${{ github.action_path }}/../../../scripts/configuration/process_coding_standards_config.py
