name: 🏁 Run Release Performance Check

on:
  issue_comment:
    types: [created]

jobs:
  dispatch-matrix-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Check permission
        id: check-write-permission
        uses: ./.github/actions/check-permissions
        with:
          minimum-permission: "write"

      - name: Dispatch Performance Testing Job
        if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/test-performance') && steps.check-write-permission.outputs.has-permission }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.RELEASE_ENGINEERING_TOKEN }}
          repository: github/codeql-coding-standards-release-engineering
          event-type: performance-test
          client-payload: '{"pr": "${{ github.event.issue.number }}"}'

      - uses: actions/github-script@v6
        if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/test-performance') && steps.check-write-permission.outputs.has-permission }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🏁 Beep Boop! Performance testing for this PR has been initiated. Please check back later for results. Note that the query package generation step must complete before testing  will start so it might be a minute. <br><br> :bulb: If you do not hear back from me please check my status! **I will report even if I fail!**'
            })
