name: 🤖 Run Matrix Check 

on:
  push:
    branches:
      - main
      - "rc/**"
      - next
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:

      - name: Dispatch Matrix Testing Job
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.RELEASE_ENGINEERING_TOKEN }}
          repository: github/codeql-coding-standards-release-engineering
          event-type: matrix-test
          client-payload: '{"pr": "${{ github.event.number  }}"}'


      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 Bip Boop! Matrix Testing for this PR has been initiated. Please check back later for results.'
            })