name: 🤖 Run Matrix Check

on:
  pull_request_target:
    types: [synchronize, opened]
    branches:
      - "matrix/**"
  workflow_dispatch:

jobs:
  dispatch-matrix-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Check permission
        id: check-write-permission
        uses: ./.github/actions/check-permissions
        with:
          minimum-permission: "write"

      - name: Dispatch Matrix Testing Job
        if: steps.check-write-permission.outputs.has-permission
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.RELEASE_ENGINEERING_TOKEN }}
          repository: github/codeql-coding-standards-release-engineering
          event-type: matrix-test
          client-payload: '{"pr": "${{ github.event.number }}"}'

      - uses: actions/github-script@v6
        if: steps.check-write-permission.outputs.has-permission
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 Beep Boop! Matrix Testing for this PR has been initiated. Please check back later for results. <br><br> :bulb: If you do not hear back from me please check my status! **I will report even if this PR does not contain files eligible for matrix testing.**'
            })
