name: Tooling unit tests

on:
  push:
    branches:
      - main
      - "rc/**"
      - next
  pull_request:
    branches:
      - main
      - "rc/**"
      - next

jobs:
  recategorization-tests:
    name: Run Guideline Recategorization tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Python dependencies
        run: pip install -r scripts/guideline_recategorization/requirements.txt

      - name: Run PyTest
        run: |
          pytest scripts/guideline_recategorization/recategorize_test.py
