name: Update Release

on:
  workflow_dispatch:
    inputs:
      head-sha:
        description: |
          The head SHA of the release PR to use for finalizing the release.
        required: true
  workflow_call:
    inputs:
      head-sha:
        type: string
        description: |
          The head SHA of the release PR to use for finalizing the release.
        required: true
    secrets:
      RELEASE_ENGINEERING_TOKEN:
        description: |
          The token to use for accessing the release engineering repository.
        required: true
env:
  HEAD_SHA: ${{ inputs.head-sha }}

jobs:

  generate-token:
      runs-on: ubuntu-latest
      outputs:
        token: ${{ steps.generate-token.outputs.token }}
      steps:
        - name: Generate token
          id: generate-token
          uses: actions/create-github-app-token@eaddb9eb7e4226c68cf4b39f167c83e5bd132b3e
          with:
            app_id: ${{ vars.AUTOMATION_APP_ID }}
            private_key: ${{ secrets.AUTOMATION_PRIVATE_KEY }}

  update-release:
    name: "Update release"
    needs: generate-token
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.head-sha }}

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r scripts/release/requirements.txt

      - name: Update release assets
        env:
          GITHUB_TOKEN: ${{ github.token }}
          RELEASE_ENGINEERING_TOKEN: ${{ generate-token.outputs.token }}
        run: |
          python scripts/release/update-release-assets.py \
            --head-sha $HEAD_SHA \
            --layout scripts/release/release-layout.yml \
            --repo "$GITHUB_REPOSITORY" \
            --github-token "$GITHUB_REPOSITORY:$GITHUB_TOKEN" "github/codeql-coding-standards-release-engineering:$RELEASE_ENGINEERING_TOKEN" \
            --skip-checkrun "release-status" \
            --skip-checks

      - name: Update release notes
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          python scripts/release/update-release-notes.py \
            --head-sha $HEAD_SHA \
            --repo "$GITHUB_REPOSITORY" \
            --github-token "$GITHUB_TOKEN"
